"""added article article_excerpt_Added

Revision ID: 1eae20bc103d
Revises: 1d308b125592
Create Date: 2023-07-24 21:21:02.297302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eae20bc103d'
down_revision = '1d308b125592'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('article_excerpt_added', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'article_excerpt_added')
    # ### end Alembic commands ###
