"""added article status

Revision ID: 238ef5d3a581
Revises: 54b03f5a4808
Create Date: 2023-07-24 18:14:28.617543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238ef5d3a581'
down_revision = '54b03f5a4808'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('article_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'article_status')
    # ### end Alembic commands ###
