"""added article status

Revision ID: 54b03f5a4808
Revises: b2b02aeb22ac
Create Date: 2023-07-24 18:08:37.544702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b03f5a4808'
down_revision = 'b2b02aeb22ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
