"""added article article_tags

Revision ID: 777bf04ac3ba
Revises: f7e8ae27bbaf
Create Date: 2023-07-24 11:23:25.672639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777bf04ac3ba'
down_revision = 'f7e8ae27bbaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('article_tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'article_tags')
    # ### end Alembic commands ###
