"""added article id

Revision ID: 82e5379fb84f
Revises: 3eb9eb436ee6
Create Date: 2023-07-24 02:54:56.963144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e5379fb84f'
down_revision = '3eb9eb436ee6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('article_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'article_id')
    # ### end Alembic commands ###
