"""added article article_status

Revision ID: 8795ae4585d3
Revises: 1eae20bc103d
Create Date: 2023-07-24 21:24:12.747263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8795ae4585d3'
down_revision = '1eae20bc103d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('article_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'article_status')
    # ### end Alembic commands ###
