"""added removed unnecessary fileds

Revision ID: 9e1662f523f7
Revises: ea1f64c99629
Create Date: 2023-07-24 18:43:13.807711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1662f523f7'
down_revision = 'ea1f64c99629'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'tags_on_wordpress_checked_and_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('tags_on_wordpress_checked_and_updated', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
