"""added article tags added

Revision ID: a71d1249b021
Revises: 238ef5d3a581
Create Date: 2023-07-24 18:20:07.121024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71d1249b021'
down_revision = '238ef5d3a581'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('artcle_tweets_added', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'artcle_tweets_added')
    # ### end Alembic commands ###
