"""added article tags added

Revision ID: bac3b1835849
Revises: a71d1249b021
Create Date: 2023-07-24 18:22:31.419515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac3b1835849'
down_revision = 'a71d1249b021'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('article_tags_added', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'article_tags_added')
    # ### end Alembic commands ###
