"""added article

Revision ID: d44e4dab4425
Revises: 82e5379fb84f
Create Date: 2023-07-24 03:16:36.117568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44e4dab4425'
down_revision = '82e5379fb84f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('article', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'article')
    # ### end Alembic commands ###
