"""added article article_image_location

Revision ID: d9d24a5a012c
Revises: 8795ae4585d3
Create Date: 2023-07-25 23:13:02.551412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d24a5a012c'
down_revision = '8795ae4585d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('article_image_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'article_image_location')
    # ### end Alembic commands ###
