"""added removed unnecessary fileds

Revision ID: ea1f64c99629
Revises: bac3b1835849
Create Date: 2023-07-24 18:36:25.876394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1f64c99629'
down_revision = 'bac3b1835849'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'article_status')
    op.drop_column('trends', 'artcle_tweets_added')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('artcle_tweets_added', sa.BOOLEAN(), nullable=True))
    op.add_column('trends', sa.Column('article_status', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
