"""added article timestamp

Revision ID: f7e8ae27bbaf
Revises: 357f31b330da
Create Date: 2023-07-24 10:02:05.090326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e8ae27bbaf'
down_revision = '357f31b330da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('timestamp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'timestamp')
    # ### end Alembic commands ###
